CREATE TABLE ESCOLA (
	ID INTEGER PRIMARY KEY,
	NOME VARCHAR (50));

CREATE TABLE ALUNO(
	ID INTEGER PRIMARY KEY,
	NOME VARCHAR (100),
	EMAIL VARCHAR (100),
	ID_ESCOLA INTEGER,
	FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID));
	
CREATE TABLE ALUNO_AUDITORIA(
	ID_ALUNO INT,
	DATA_INSERT TIMESTAMP);

CREATE OR REPLACE FUNCTION ALUNO_LOG_FUNC()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
-- TO EDIT
INSERT INTO ALUNO_AUDITORIA(ID_ALUNO, DATA_INSERT) VALUES (NEW.ID, CURRENT_TIMESTAMP);
RETURN NEW;
END;
$$

CREATE TRIGGER LOG_TRIGGER
AFTER INSERT ON aluno
FOR EACH ROW
EXECUTE PROCEDURE ALUNO_LOG_FUNC();

INSERT INTO ESCOLA VALUES (1, 'Resilia');

INSERT INTO ALUNO VALUES (1, 'Rafael', 'rafa_anginho@hotmail.com', 1)

SELECT * FROM ALUNO
SELECT * FROM ESCOLA
SELECT * FROM ALUNO_AUDITORIA